# Generated by Django 4.2.7 on 2023-12-10 00:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_audit_date_alter_audit_function_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audit",
            old_name="function_id",
            new_name="function",
        ),
        migrations.RenameField(
            model_name="audit",
            old_name="user_name",
            new_name="user",
        ),
    ]
