# Generated by Django 4.2.7 on 2023-12-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
