# Generated by Django 4.2.7 on 2023-12-07 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module', '0002_alter_module_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.module')),
            ],
        ),
    ]
