# Generated by Django 4.2.7 on 2023-12-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("function", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="function",
            old_name="module_id",
            new_name="module",
        ),
        migrations.AlterField(
            model_name="function",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
